output_dir: ~/flock/output-entity

dataset:
  class: {{ dataset }}
  root: ~/flock/kg-datasets-entity/

model:
  class: Flock
  verbose: False
  test_samples: 2
  # random walk
  walk_num: 512
  walk_len: 128
  record_neighbors: False
  # refinements
  refinements: 6
  attention_scatter: True
  attention_scatter_n_heads: 4
  additive_refinement: True
  embed_only_first_refinement: False
  embedding_tying_across_refinements: False
  parameter_tying_across_refinements: False
  # sequence network
  net: gru
  hidden_dim: 64
  n_layers: 1
  dtype: float32

task:
  name: TransductiveInference
  num_negative: 256
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, mrr-tail, hits@10-tail]

optimizer:
  class: AdamW
  lr: 5.0e-4

train:
  gpus: {{ gpus }}
  batch_size: 4
  test_batch_size: 2
  num_epoch: {{ epochs }}
  log_interval: 100
  batch_per_epoch: {{ bpe }}

checkpoint: {{ ckpt }}